=== Luis-Rguez/proyectoIntermodular/LenguajesMarcas/ArchivosXMLyXSD/esquemaAjedrez.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- TORNEOS -->
    <xs:element name="torneos">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="torneo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="fechaInicio" type="xs:date"/>
                            <xs:element name="fechaFin" type="xs:date"/>

                            <xs:element name="partidas">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="partida" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>

                                                    <xs:element name="ronda" type="xs:int"/>
                                                    <xs:element name="mesa" type="xs:int"/>

                                                    <xs:element name="blancas">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre" type="xs:string"/>
                                                                <xs:element name="resultado" type="xs:string"/>
                                                            </xs:sequence>
                                                            <xs:attribute name="jugadorId" type="xs:int" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>

                                                    <xs:element name="negras">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre" type="xs:string"/>
                                                                <xs:element name="resultado" type="xs:string"/>
                                                            </xs:sequence>
                                                            <xs:attribute name="jugadorId" type="xs:int" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>

                                                    <xs:element name="arbitro" type="xs:string"/>

                                                    <xs:element name="movimientos">
                                                        <xs:complexType>
                                                            <xs:sequence>

                                                                <xs:element name="movimiento" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="blancas" type="xs:string"/>
                                                                            <xs:element name="negras" type="xs:string"/>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="id" type="xs:int" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>

                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>

                                                </xs:sequence>

                                                <xs:attribute name="id" type="xs:int" use="required"/>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="id" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- USUARIOS -->
    <xs:element name="usuarios">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellido" type="xs:string"/>
                            <xs:element name="dni" type="xs:string"/>
                            <xs:element name="mail" type="xs:string"/>
                            <xs:element name="telefono" type="xs:string"/>
                            <xs:element name="password" type="xs:string"/>
                            <xs:element name="edad" type="xs:int"/>

                        </xs:sequence>

                        <xs:attribute name="id" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Luis-Rguez/proyectoIntermodular/LenguajesMarcas/ArchivosXMLyXSD/torneos.xml
<?xml version="1.0" encoding="UTF-8"?>

<torneos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="esquemaAjedrez.xsd">

    <torneo id="1">
        <nombre>Master Chess</nombre>
        <fechaInicio>2026-04-10</fechaInicio>
        <fechaFin>2026-04-20</fechaFin>

        <partidas>

            <partida id="1">
                <ronda>1</ronda>
                <mesa>1</mesa>

                <blancas jugadorId="1">
                    <nombre>Mario Kart</nombre>
                    <resultado>1</resultado>
                </blancas>

                <negras jugadorId="2">
                    <nombre>Luigui Mansion</nombre>
                    <resultado>0</resultado>
                </negras>

                <arbitro>Antonio López</arbitro>

                <movimientos>

                    <movimiento id="1">
                        <blancas>e4</blancas>
                        <negras>e5</negras>
                    </movimiento>

                    <movimiento id="2">
                        <blancas>Nf3</blancas>
                        <negras>Nc6</negras>
                    </movimiento>

                </movimientos>

            </partida>

            <partida id="2">
                <ronda>1</ronda>
                <mesa>2</mesa>

                <blancas jugadorId="3">
                    <nombre>Peich Princesa</nombre>
                    <resultado>0.5</resultado>
                </blancas>

                <negras jugadorId="4">
                    <nombre>Toad Champi</nombre>
                    <resultado>0.5</resultado>
                </negras>

                <arbitro>María Sánchez</arbitro>

                <movimientos>

                    <movimiento id="3">
                        <blancas>d4</blancas>
                        <negras>d5</negras>
                    </movimiento>

                </movimientos>

            </partida>

        </partidas>

    </torneo>

</torneos>
